### PR TITLE
Add Troubleshooting steps

### PR DESCRIPTION
**Pull request by cob16**

### CODE REVIEW

**Review by zemanlx — DISMISSED** [review]

**Comment by zemanlx** [comment]
retest this please

**Comment by zemanlx** [comment]
retest this please

**Comment by zemanlx** [comment]
retest this please

**Comment by zemanlx** [comment]
retest this please

**Comment by zemanlx** [comment]
retest this please

**Review by jonnyshaw89 — DISMISSED** [review]

**Review by zemanlx — APPROVED** [review]

**Pull request merged**
